import Foundation
import IOKit
import IOKit.hid
import Dispatch

// MARK: - Embedded tables (auto-generated by rgb.py --emit-swift; do not hand-edit)
let LED_POSITIONS: [Int32] = [  // index -> (x*1000, y*1000); -1 = gap
    500, 0, // 0: ESC
    500, 1000, // 1: BACKTICK
    750, 2000, // 2: TAB
    875, 3000, // 3: CAPSLOCK
    1125, 4000, // 4: LSHIFT
    875, 5000, // 5: LCTRL
    -1, -1, // 6: (gap)
    1500, 1000, // 7: 1
    1750, 2000, // 8: Q
    1875, 3000, // 9: A
    2625, 4000, // 10: Z
    1875, 5000, // 11: LWIN
    2000, 0, // 12: F1
    2500, 1000, // 13: 2
    2750, 2000, // 14: W
    2875, 3000, // 15: S
    3625, 4000, // 16: X
    2875, 5000, // 17: LALT
    3000, 0, // 18: F2
    3500, 1000, // 19: 3
    3750, 2000, // 20: E
    3875, 3000, // 21: D
    4625, 4000, // 22: C
    -1, -1, // 23: (gap)
    4000, 0, // 24: F3
    4500, 1000, // 25: 4
    4750, 2000, // 26: R
    4875, 3000, // 27: F
    5625, 4000, // 28: V
    -1, -1, // 29: (gap)
    5000, 0, // 30: F4
    5500, 1000, // 31: 5
    5750, 2000, // 32: T
    5875, 3000, // 33: G
    6625, 4000, // 34: B
    6500, 5000, // 35: SPACE
    6500, 0, // 36: F5
    6500, 1000, // 37: 6
    6750, 2000, // 38: Y
    6875, 3000, // 39: H
    7625, 4000, // 40: N
    -1, -1, // 41: (gap)
    7500, 0, // 42: F6
    7500, 1000, // 43: 7
    7750, 2000, // 44: U
    7875, 3000, // 45: J
    8625, 4000, // 46: M
    -1, -1, // 47: (gap)
    8500, 0, // 48: F7
    8500, 1000, // 49: 8
    8750, 2000, // 50: I
    8875, 3000, // 51: K
    9625, 4000, // 52: COMMA
    10250, 5000, // 53: FN
    9500, 0, // 54: F8
    9500, 1000, // 55: 9
    9750, 2000, // 56: O
    9875, 3000, // 57: L
    10625, 4000, // 58: PERIOD
    11250, 5000, // 59: RCTRL
    11000, 0, // 60: F9
    10500, 1000, // 61: 0
    10750, 2000, // 62: P
    10875, 3000, // 63: SEMICOLON
    11625, 4000, // 64: SLASH
    -1, -1, // 65: (gap)
    12000, 0, // 66: F10
    11500, 1000, // 67: MINUS
    11750, 2000, // 68: LEFTBRACKET
    11875, 3000, // 69: QUOTE
    13375, 4000, // 70: RSHIFT
    -1, -1, // 71: (gap)
    13000, 0, // 72: F11
    12500, 1000, // 73: EQUAL
    12750, 2000, // 74: RIGHTBRACKET
    -1, -1, // 75: (gap)
    -1, -1, // 76: (gap)
    14000, 5000, // 77: LEFT
    14000, 0, // 78: F12
    14000, 1000, // 79: BACKSPACE
    14000, 2000, // 80: BACKSLASH
    13625, 3000, // 81: ENTER
    15000, 4000, // 82: UP
    15000, 5000, // 83: DOWN
    -1, -1, // 84: (gap)
    15500, 1000, // 85: DEL
    15500, 2000, // 86: PGUP
    15500, 3000, // 87: PGDN
    16000, 4000, // 88: END
    16000, 5000, // 89: RIGHT
]
let LED_KEY_NAMES: [Int32: String] = [  // LED index -> key name
    0: "ESC",
    1: "BACKTICK",
    2: "TAB",
    3: "CAPSLOCK",
    4: "LSHIFT",
    5: "LCTRL",
    7: "1",
    8: "Q",
    9: "A",
    10: "Z",
    11: "LWIN",
    12: "F1",
    13: "2",
    14: "W",
    15: "S",
    16: "X",
    17: "LALT",
    18: "F2",
    19: "3",
    20: "E",
    21: "D",
    22: "C",
    24: "F3",
    25: "4",
    26: "R",
    27: "F",
    28: "V",
    30: "F4",
    31: "5",
    32: "T",
    33: "G",
    34: "B",
    35: "SPACE",
    36: "F5",
    37: "6",
    38: "Y",
    39: "H",
    40: "N",
    42: "F6",
    43: "7",
    44: "U",
    45: "J",
    46: "M",
    48: "F7",
    49: "8",
    50: "I",
    51: "K",
    52: "COMMA",
    53: "FN",
    54: "F8",
    55: "9",
    56: "O",
    57: "L",
    58: "PERIOD",
    59: "RCTRL",
    60: "F9",
    61: "0",
    62: "P",
    63: "SEMICOLON",
    64: "SLASH",
    66: "F10",
    67: "MINUS",
    68: "LEFTBRACKET",
    69: "QUOTE",
    70: "RSHIFT",
    72: "F11",
    73: "EQUAL",
    74: "RIGHTBRACKET",
    77: "LEFT",
    78: "F12",
    79: "BACKSPACE",
    80: "BACKSLASH",
    81: "ENTER",
    82: "UP",
    83: "DOWN",
    85: "DEL",
    86: "PGUP",
    87: "PGDN",
    88: "END",
    89: "RIGHT",
]
let KEY_POSITIONS: [String: (x: Int32, y: Int32)] = [
    "0": (10500, 1000),
    "1": (1500, 1000),
    "2": (2500, 1000),
    "3": (3500, 1000),
    "4": (4500, 1000),
    "5": (5500, 1000),
    "6": (6500, 1000),
    "7": (7500, 1000),
    "8": (8500, 1000),
    "9": (9500, 1000),
    "A": (1875, 3000),
    "B": (6625, 4000),
    "BACKSLASH": (14000, 2000),
    "BACKSPACE": (14000, 1000),
    "BACKTICK": (500, 1000),
    "C": (4625, 4000),
    "CAPSLOCK": (875, 3000),
    "COMMA": (9625, 4000),
    "D": (3875, 3000),
    "DEL": (15500, 1000),
    "DOWN": (15000, 5000),
    "E": (3750, 2000),
    "END": (16000, 4000),
    "ENTER": (13625, 3000),
    "EQUAL": (12500, 1000),
    "ESC": (500, 0),
    "F": (4875, 3000),
    "F1": (2000, 0),
    "F10": (12000, 0),
    "F11": (13000, 0),
    "F12": (14000, 0),
    "F2": (3000, 0),
    "F3": (4000, 0),
    "F4": (5000, 0),
    "F5": (6500, 0),
    "F6": (7500, 0),
    "F7": (8500, 0),
    "F8": (9500, 0),
    "F9": (11000, 0),
    "FN": (10250, 5000),
    "G": (5875, 3000),
    "H": (6875, 3000),
    "I": (8750, 2000),
    "J": (7875, 3000),
    "K": (8875, 3000),
    "L": (9875, 3000),
    "LALT": (2875, 5000),
    "LCTRL": (875, 5000),
    "LEFT": (14000, 5000),
    "LEFTBRACKET": (11750, 2000),
    "LSHIFT": (1125, 4000),
    "LWIN": (1875, 5000),
    "M": (8625, 4000),
    "MINUS": (11500, 1000),
    "N": (7625, 4000),
    "O": (9750, 2000),
    "P": (10750, 2000),
    "PERIOD": (10625, 4000),
    "PGDN": (15500, 3000),
    "PGUP": (15500, 2000),
    "Q": (1750, 2000),
    "QUOTE": (11875, 3000),
    "R": (4750, 2000),
    "RCTRL": (11250, 5000),
    "RIGHT": (16000, 5000),
    "RIGHTBRACKET": (12750, 2000),
    "RSHIFT": (13375, 4000),
    "S": (2875, 3000),
    "SEMICOLON": (10875, 3000),
    "SLASH": (11625, 4000),
    "SPACE": (6500, 5000),
    "T": (5750, 2000),
    "TAB": (750, 2000),
    "U": (7750, 2000),
    "UP": (15000, 4000),
    "V": (5625, 4000),
    "W": (2750, 2000),
    "X": (3625, 4000),
    "Y": (6750, 2000),
    "Z": (2625, 4000),
]
let HID_USAGE_TO_KEY: [Int32: String] = [
    4: "A",
    5: "B",
    6: "C",
    7: "D",
    8: "E",
    9: "F",
    10: "G",
    11: "H",
    12: "I",
    13: "J",
    14: "K",
    15: "L",
    16: "M",
    17: "N",
    18: "O",
    19: "P",
    20: "Q",
    21: "R",
    22: "S",
    23: "T",
    24: "U",
    25: "V",
    26: "W",
    27: "X",
    28: "Y",
    29: "Z",
    30: "1",
    31: "2",
    32: "3",
    33: "4",
    34: "5",
    35: "6",
    36: "7",
    37: "8",
    38: "9",
    39: "0",
    40: "ENTER",
    41: "ESC",
    42: "BACKSPACE",
    43: "TAB",
    44: "SPACE",
    45: "MINUS",
    46: "EQUAL",
    47: "LEFTBRACKET",
    48: "RIGHTBRACKET",
    49: "BACKSLASH",
    51: "SEMICOLON",
    52: "QUOTE",
    53: "BACKTICK",
    54: "COMMA",
    55: "PERIOD",
    56: "SLASH",
    57: "CAPSLOCK",
    58: "F1",
    59: "F2",
    60: "F3",
    61: "F4",
    62: "F5",
    63: "F6",
    64: "F7",
    65: "F8",
    66: "F9",
    67: "F10",
    68: "F11",
    69: "F12",
    74: "HOME",
    75: "PGUP",
    76: "DEL",
    77: "END",
    78: "PGDN",
    79: "RIGHT",
    80: "LEFT",
    81: "DOWN",
    82: "UP",
    224: "LCTRL",
    225: "LSHIFT",
    226: "LALT",
    227: "LWIN",
    228: "RCTRL",
    229: "RSHIFT",
    230: "RALT",
    231: "RWIN",
]

// MARK: - Configuration

let TARGET_VENDOR_ID = 0x258A
let TARGET_PRODUCT_ID = 0x010C
let LED_COUNT = 90          // indices 0..89 for the AULA F75 (model id 0xCD)
let REPORT_SIZE = 520

// Ripple parameters (must match rgb.py)
let SPEED: Double = 40.0    // wavefront speed, key-units/s
let SIGMA: Double = 0.6     // ring half-width, key-units
let TAU: Double = 0.8       // amplitude decay time-constant, s
let MAX_AGE: Double = 2.5   // drop ripple after this many seconds

// MARK: - Ripple state (shared between the IOHID input callback and the frame loop)

struct Ripple { let cx: Double; let cy: Double; let t0: Double }
let stateLock = NSLock()
var ripples: [Ripple] = []
var keyAdvance = false      // map mode: any keypress advances the lit LED
var logKeys = false         // --log-keys: print each detected keypress

// MARK: - HID helpers

func entryID(_ d: IOHIDDevice) -> UInt64 {
    let s = IOHIDDeviceGetService(d); var e: UInt64 = 0
    IORegistryEntryGetRegistryEntryID(s, &e); return e
}
func pInt(_ d: IOHIDDevice, _ k: String) -> Int? {
    guard let v = IOHIDDeviceGetProperty(d, k as CFString) as? NSNumber else { return nil }
    return v.intValue
}
func pStr(_ d: IOHIDDevice, _ k: String) -> String? {
    return IOHIDDeviceGetProperty(d, k as CFString) as? String
}

func now() -> Double { return CFAbsoluteTimeGetCurrent() }

// Build a 520-byte feature report for the given 90-LED colour buffer.
func makeFrame(_ colors: [UInt8]) -> [UInt8] {
    var buf = [UInt8](repeating: 0, count: REPORT_SIZE)
    buf[0] = 0x06
    buf[1] = 0x08
    buf[4] = 0x01
    buf[6] = 0x7A
    buf[7] = 0x01
    let n = min(colors.count / 3, LED_COUNT)
    for i in 0..<n {
        buf[8 + i*3 + 0] = colors[i*3 + 0]
        buf[8 + i*3 + 1] = colors[i*3 + 1]
        buf[8 + i*3 + 2] = colors[i*3 + 2]
    }
    return buf
}

func sendFrame(_ dev: IOHIDDevice, _ colors: [UInt8]) -> Bool {
    var frame = makeFrame(colors)
    let res = IOHIDDeviceSetReport(dev, kIOHIDReportTypeFeature, 0x06, &frame, REPORT_SIZE)
    return res == kIOReturnSuccess
}

// READ-ONLY model-id query. Returns the model id byte (0xCD = AULA F75) or -1.
func queryModelId(_ dev: IOHIDDevice) -> Int {
    var cmd = [UInt8](repeating: 0, count: REPORT_SIZE)
    cmd[0] = 0x06; cmd[1] = 0x82; cmd[2] = 0x01; cmd[3] = 0x00
    cmd[4] = 0x01; cmd[5] = 0x00; cmd[6] = 0x06
    let setRes = IOHIDDeviceSetReport(dev, kIOHIDReportTypeFeature, 0x06, &cmd, REPORT_SIZE)
    guard setRes == kIOReturnSuccess else { return -1 }
    var resp = [UInt8](repeating: 0, count: REPORT_SIZE)
    resp[0] = 0x06
    var rlen: CFIndex = REPORT_SIZE
    let getRes = IOHIDDeviceGetReport(dev, kIOHIDReportTypeFeature, 0x06, &resp, &rlen)
    guard getRes == kIOReturnSuccess else { return -1 }
    return Int(resp[13])
}

func solidColors(_ r: UInt8, _ g: UInt8, _ b: UInt8) -> [UInt8] {
    var out = [UInt8](repeating: 0, count: LED_COUNT * 3)
    for i in 0..<LED_COUNT { out[i*3] = r; out[i*3+1] = g; out[i*3+2] = b }
    return out
}

// MARK: - Ripple frame computation (mirrors rgb.py ripple_color)

func computeColors(idleR: UInt8, idleG: UInt8, idleB: UInt8, t: Double) -> [UInt8] {
    var out = [UInt8](repeating: 0, count: LED_COUNT * 3)
    stateLock.lock()
    let active = ripples.filter { (t - $0.t0) <= MAX_AGE }
    stateLock.unlock()

    for i in 0..<LED_COUNT {
        let x = Double(LED_POSITIONS[i*2]) / 1000.0
        let y = Double(LED_POSITIONS[i*2+1]) / 1000.0
        var r = Double(idleR), g = Double(idleG), b = Double(idleB)
        if x >= 0 {
            var total = 0.0
            for rp in active {
                let age = t - rp.t0
                if age < 0 { continue }
                let d = ((x - rp.cx) * (x - rp.cx) + (y - rp.cy) * (y - rp.cy)).squareRoot()
                let radius = SPEED * age
                let amp = exp(-age / TAU)
                total += amp * exp(-((d - radius) * (d - radius)) / (2.0 * SIGMA * SIGMA))
            }
            total = min(1.0, total)
            r += (255.0 - r) * total
            g += (255.0 - g) * total
            b += (255.0 - b) * total
        }
        out[i*3]   = UInt8(min(255, max(0, Int(r.rounded()))))
        out[i*3+1] = UInt8(min(255, max(0, Int(g.rounded()))))
        out[i*3+2] = UInt8(min(255, max(0, Int(b.rounded()))))
    }
    return out
}

// MARK: - Subcommands

func usage() -> Never {
    let s = """
    rgb — reactive RGB for the SinoWealth "Gaming Keyboard" (258a:010c, AULA F75)

    usage: rgb <command> [args]

      probe                        read-only: enumerate interfaces + query model id
      selftest                     prove GET+SET+INPUT: model id, colour frames, 6s keypress listen
      solid <R> <G> <B>            steady solid colour (Ctrl+C to stop)
      off                          lights out (black, Ctrl+C to stop)
      map [--auto <ms>]            light each LED one at a time to build the index->key map
                                   (default: advance on any keypress; --auto N = fixed delay)
      ripple <R> <G> <B> [--fps N] reactive effect: idle colour + white ripple on keypress
                                   (default fps 60)

    All colour commands run in the foreground and restore the idle/solid colour on exit.
    """
    fputs(s, stderr)
    exit(2)
}

// MARK: - Main

let args = Array(CommandLine.arguments.dropFirst())
if args.isEmpty { usage() }

// Unbuffered stdout so a detached run (nohup > log) shows output immediately.
setvbuf(stdout, nil, _IONBF, 0)

// Parse command + common numeric args.
let cmd = args[0]
var r = 20, g = 40, b = 120
if cmd == "ripple" && args.count >= 4 { r = Int(args[1]) ?? r; g = Int(args[2]) ?? g; b = Int(args[3]) ?? b }
if cmd == "solid" && args.count >= 4 { r = Int(args[1]) ?? r; g = Int(args[2]) ?? g; b = Int(args[3]) ?? b }
var fps = 60
if let fi = args.firstIndex(of: "--fps"), fi + 1 < args.count { fps = Int(args[fi+1]) ?? 60 }
var mapAutoMs = 0
if cmd == "map", let ai = args.firstIndex(of: "--auto"), ai + 1 < args.count { mapAutoMs = Int(args[ai+1]) ?? 0 }
if args.contains("--log-keys") { logKeys = true }

// Build the IOHIDManager matching the keyboard.
let manager = IOHIDManagerCreate(kCFAllocatorDefault, IOOptionBits(kIOHIDOptionsTypeNone))
IOHIDManagerSetDeviceMatching(manager, [kIOHIDVendorIDKey: TARGET_VENDOR_ID, kIOHIDProductIDKey: TARGET_PRODUCT_ID] as CFDictionary)

var seen: [UInt64: IOHIDDevice] = [:]
let matchCb: IOHIDDeviceCallback = { _, _, _, d in seen[entryID(d)] = d }
IOHIDManagerRegisterDeviceMatchingCallback(manager, matchCb, nil)

let inputCb: IOHIDValueCallback = { _, _, _, value in
    let element = IOHIDValueGetElement(value)
    let page = IOHIDElementGetUsagePage(element)
    let usage = IOHIDElementGetUsage(element)
    let v = IOHIDValueGetIntegerValue(value)
    // Only keyboard-page key PRESSES (value == 1) matter.
    guard page == 0x07, v == 1 else { return }
    if let key = HID_USAGE_TO_KEY[Int32(usage)], let p = KEY_POSITIONS[key] {
        let cx = Double(p.x) / 1000.0, cy = Double(p.y) / 1000.0
        stateLock.lock()
        ripples.append(Ripple(cx: cx, cy: cy, t0: now()))
        keyAdvance = true
        let doLog = logKeys
        stateLock.unlock()
        if doLog {
            print(String(format: "KEYPRESS %@ usage=0x%02X pos=(%.3f, %.3f)", key, usage, cx, cy))
            fflush(stdout)
        }
    }
}
IOHIDManagerRegisterInputValueCallback(manager, inputCb, nil)
IOHIDManagerScheduleWithRunLoop(manager, CFRunLoopGetCurrent(), CFRunLoopMode.defaultMode.rawValue)
let openRes = IOHIDManagerOpen(manager, IOOptionBits(kIOHIDOptionsTypeNone))
if openRes != kIOReturnSuccess {
    fputs("rgb: IOHIDManagerOpen failed 0x\(String(openRes, radix: 16))\n", stderr)
    exit(3)
}
// Populate 'seen'.
CFRunLoopRunInMode(CFRunLoopMode.defaultMode, 1.5, false)

guard let rgbDev = seen.values.first(where: { (pInt($0, kIOHIDMaxFeatureReportSizeKey) ?? 0) >= REPORT_SIZE }) else {
    fputs("rgb: no RGB interface found (maxFeature >= \(REPORT_SIZE)). Is the keyboard plugged in?\n", stderr)
    exit(2)
}
IOHIDDeviceOpen(rgbDev, IOOptionBits(kIOHIDOptionsTypeNone))

// --- probe ---
if cmd == "probe" {
    print("matched \(seen.count) interface(s):")
    for d in seen.values.sorted(by: { entryID($0) < entryID($1) }) {
        let up = pInt(d, kIOHIDDeviceUsagePageKey) ?? 0
        let u  = pInt(d, kIOHIDDeviceUsageKey) ?? 0
        let maxIn  = pInt(d, kIOHIDMaxInputReportSizeKey) ?? 0
        let maxFeat = pInt(d, kIOHIDMaxFeatureReportSizeKey) ?? 0
        let prod = pStr(d, kIOHIDProductKey) ?? "?"
        print(String(format: "  iface=0x%llx usagePage=0x%02X usage=0x%02X maxIn=%d maxFeature=%d product=\"%@\"",
                     entryID(d), up, u, maxIn, maxFeat, prod))
    }
    let mid = queryModelId(rgbDev)
    if mid >= 0 {
        let name = (mid == 0xCD) ? "AULA F75" : (mid == 0xA4 ? "AULA F99" : (mid == 0x0B ? "AULA F87 Pro" : (mid == 0xA3 ? "LEOBOG Hi75C Pro" : "unknown")))
        print(String(format: "model_id = 0x%02X (%@)", mid, name))
    } else {
        print("model_id query failed")
    }
    IOHIDDeviceClose(rgbDev, IOOptionBits(kIOHIDOptionsTypeNone))
    exit(0)
}

// --- selftest: prove GET (model id), SET (frames), and INPUT (keypress) live ---
if cmd == "selftest" {
    let mid = queryModelId(rgbDev)
    print(String(format: "selftest model_id = 0x%02X (%@)", mid, mid == 0xCD ? "AULA F75" : "?"))

    let frames: [(String, [UInt8])] = [
        ("red", solidColors(255, 0, 0)),
        ("green", solidColors(0, 255, 0)),
        ("blue", solidColors(0, 0, 255)),
        ("off", solidColors(0, 0, 0)),
    ]
    for (name, cols) in frames {
        var frame = makeFrame(cols)
        let a = CFAbsoluteTimeGetCurrent()
        let res = IOHIDDeviceSetReport(rgbDev, kIOHIDReportTypeFeature, 0x06, &frame, REPORT_SIZE)
        let b = CFAbsoluteTimeGetCurrent()
        let ok = res == kIOReturnSuccess
        print(String(format: "selftest send %@ -> 0x%08X %@  (%.2f ms)", name, res, ok ? "OK" : "FAIL", (b-a)*1000))
        fflush(stdout)
        usleep(300_000)
    }
    _ = sendFrame(rgbDev, solidColors(0, 0, 0))

    print("selftest: listening for keypresses for 6s — type on the keyboard now")
    logKeys = true
    let deadline = now() + 6.0
    while now() < deadline {
        CFRunLoopRunInMode(CFRunLoopMode.defaultMode, 0.1, false)
    }
    logKeys = false
    IOHIDDeviceClose(rgbDev, IOOptionBits(kIOHIDOptionsTypeNone))
    print("selftest done.")
    exit(0)
}

// Async-signal-safe stop flag. The signal handler only sets this sig_atomic_t
// (a plain write is async-signal-safe); the background frame loop polls it and
// restores the colour before exiting. signal()+sig_atomic_t is bulletproof where
// DispatchSource signal sources proved flaky for SIGTERM.
var g_stop: sig_atomic_t = 0
func handleStopSignal(_ sig: Int32) { g_stop = 1 }
signal(SIGINT, handleStopSignal)
signal(SIGTERM, handleStopSignal)

// Final colour to leave on the board as we exit (idle for ripple, colour for solid, black for off/map).
let finalColors: [UInt8]
if cmd == "off" || cmd == "map" {
    finalColors = solidColors(0, 0, 0)
} else {
    finalColors = solidColors(UInt8(r), UInt8(g), UInt8(b))
}

// The continuous loop (map / solid / off / ripple) runs on a BACKGROUND thread
// so the MAIN thread can CFRunLoopRun() and service the IOHID input callbacks.
// Without this, keypresses never arrive (the while+usleep loop doesn't pump the
// run loop), so the ripple would sit idle forever.
let frameInterval = 1.0 / Double(max(1, fps))

DispatchQueue.global(qos: .userInteractive).async {
    if cmd == "map" {
        print("map mode: lighting each LED one at a time (Ctrl+C to stop).")
        if mapAutoMs > 0 { print("auto-advance every \(mapAutoMs) ms") } else { print("press any key to advance") }
        var i = 0
        while g_stop == 0 {
            var cols = [UInt8](repeating: 0, count: LED_COUNT * 3)
            cols[i*3] = 255; cols[i*3+1] = 255; cols[i*3+2] = 255
            _ = sendFrame(rgbDev, cols)
            let keyName = LED_KEY_NAMES[Int32(i)]
            print(String(format: "LED %2d  %@", i, keyName ?? "(gap/unmapped)"))
            if mapAutoMs > 0 {
                usleep(useconds_t(mapAutoMs * 1000))
            } else {
                stateLock.lock(); keyAdvance = false; stateLock.unlock()
                while g_stop == 0 {
                    stateLock.lock(); let adv = keyAdvance; stateLock.unlock()
                    if adv { break }
                    usleep(10_000)
                }
            }
            i = (i + 1) % LED_COUNT
        }
        _ = sendFrame(rgbDev, finalColors)
        IOHIDDeviceClose(rgbDev, IOOptionBits(kIOHIDOptionsTypeNone))
        print("map stopped — lights off.")
        exit(0)
    }

    print(cmd == "off" ? "off: lights out (Ctrl+C to stop)" :
          cmd == "solid" ? "solid \(r) \(g) \(b) (Ctrl+C to stop)" :
          "ripple \(r) \(g) \(b) @ \(fps) fps (Ctrl+C to stop)")

    var lastFrame = now()
    while g_stop == 0 {
        let t = now()
        let colors: [UInt8]
        if cmd == "ripple" {
            colors = computeColors(idleR: UInt8(r), idleG: UInt8(g), idleB: UInt8(b), t: t)
        } else {
            colors = finalColors
        }
        _ = sendFrame(rgbDev, colors)
        let elapsed = now() - lastFrame
        lastFrame = now()
        if elapsed < frameInterval {
            usleep(useconds_t((frameInterval - elapsed) * 1_000_000))
        }
    }

    // Restore the idle/solid colour on exit, then close.
    _ = sendFrame(rgbDev, finalColors)
    IOHIDDeviceClose(rgbDev, IOOptionBits(kIOHIDOptionsTypeNone))
    print("stopped — restored colour \(r) \(g) \(b).")
    exit(0)
}

// Main thread: service the IOHID input callbacks (keypress -> ripple) forever,
// until the background loop calls exit().
CFRunLoopRun()
